site_name: "Bintracker Documentation"

repo_name: bintracker/bintracker
repo_url: 'https://github.com/bintracker/bintracker'
edit_uri: ""
docs_dir: 'build/gendoc/'

theme:
  name: 'material'
  custom_dir: 'resources/material/'
  font: false
  favicon: 'assets/images/favicon.png'
  language: en
  palette:
    primary: teal
    accent: cyan
  logo: 'assets/images/logo.svg'
  feature:
    tabs: false
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html

extra:
  hljs_languages:
    - scheme

plugins:
  - localsearch

extra_javascript:
  - search/search_index.js

site_dir: 'build/documentation'

nav:
  - Main: index.md
  - Quickstart: quickstart.md
  - User Manual:
      - Introduction: about.md
      - Setup: setup.md
      - Configuration: configuration.md
      - "Key Bindings": keybindings.md
      - "Editing Modules": editing.md
      - "The REPL": repl.md
  - "Developer Documentation":
      - "Getting Started": hacking.md
      - Quickref: quickref.md
      - "Style Guide": style-guide.md
      - "TODO List": TODO.md
      - "Writing Plugins": writing-plugins.md
      - "Bintracker API":
         - "bintracker-core": 'generated/bintracker-core.md'
         - "bt-types": 'generated/bt-types.md'
         - "bt-state": 'generated/bt-state.md'
         - "bt-gui": 'generated/bt-gui.md'
         - "bt-gui-lolevel": 'generated/bt-gui-lolevel.md'
         - "bt-emulation": 'generated/bt-emulation.md'
         - "bt-db": 'generated/bt-db.md'
      - MDAL:
        - Introduction: 'mdal-introduction.md'
        - "Modules (MMOD)": 'MMOD_SPECIFICATION.md'
        - "Engine Definitions (MDEF)": 'MDEF_SPECIFICATION.md'
        - "libmdal API":
          - "mdal": 'generated/mdal.md'
          - "md-types": 'generated/md-types.md'
          - "md-helpers": 'generated/md-helpers.md'
          - "md-config" : 'generated/md-config.md'
          - "md-command": 'generated/md-command.md'
          - "md-parser": 'generated/md-parser.md'
          - utils:
              - "md-note-table": 'generated/utils/md-note-table.md'
      - "Schemta Assembler":
          - Introduction: 'schemta.md'
          - Schemta API: 'generated/schemta.md'
      - Examples: examples.md
  - "Frequently Asked Questions": FAQ.md
  - Contributing: contributing.md
  - "Code of Conduct": CODE_OF_CONDUCT.md
  - "Fan Art": fanart.md

markdown_extensions:
  - codehilite

use_directory_urls: False
