site_name: "Bintracker Documentation"

repo_name: utz82/bintracker
repo_url: 'https://github.com/utz82/bintracker'
edit_uri: ""

theme:
  name: 'material'
  custom_dir: 'resources/material/'
  font: false
  favicon: 'assets/images/favicon.png'
  language: en
  palette:
    primary: teal
    accent: cyan
  logo: 'assets/images/logo.svg'
  feature:
    tabs: false
  include_search_page: false
  search_index_only: true
  static_templates:
    - 404.html

extra:
  hljs_languages:
    - scheme

plugins:
  - localsearch

extra_javascript:
  - search/search_index.js

site_dir: 'documentation'

nav:
  - Overview: index.md
  - User Manual:
      - Setup: setup.md
      - "Getting Started": getting-started.md
      - Configuration: configuration.md
      - "Using The Console": console.md
  - "Hacking Bintracker":
      - "Getting Started": hacking.md
      - "Style Guide": style-guide.md
      - "Bintracker API":
          - "bintracker-core": 'generated/bintracker-core.md'
          - "bt-types": 'generated/bt-types.md'
          - "bt-state": 'generated/bt-state.md'
          - "bt-gui": 'generated/bt-gui.md'
          - "bt-emulation": 'generated/bt-emulation.md'
          - "bt-db": 'generated/bt-db.md'
  - MDAL:
      - Introduction: 'libmdal/index.md'
      - MDMOD: 'libmdal/MDMOD_SPECIFICATION.md'
      - MDCONF: 'libmdal/MDCONF_SPECIFICATION.md'
      - "libmdal API":
          - "mdal": 'libmdal/generated/mdal.md'
          - "md-types": 'libmdal/generated/md-types.md'
          - "md-helpers": 'libmdal/generated/md-helpers.md'
          - "md-config" : 'libmdal/generated/md-config.md'
          - "md-command": 'libmdal/generated/md-command.md'
          - "md-parser": 'libmdal/generated/md-parser.md'
          - utils:
              - "md-note-table": 'libmdal/generated/utils/md-note-table.md'
      - "Schemta Assembler":
          - Introduction: 'libmdal/schemta.md'
          - Schemta API: 'libmdal/generated/schemta.md'

markdown_extensions:
  - codehilite

use_directory_urls: False
