site_name: "Bintracker NG"

theme:
  name: 'material'
  hljs_languages:
    - scheme
    - xml

site_dir: 'documentation'

nav:
  - Home: index.md
  - User Manual:
      - Setup: setup.md
      - "Getting Started": getting-started.md
      - Configuration: configuration.md
      - "Using The Console": console.md
  - "Hacking Bintracker":
      - "Getting Started": hacking.md
      - "Bintracker API":
          - "bintracker-core": 'generated/bintracker-core.md'
          - "bt-gui": 'generated/bt-gui.md'
          - "bt-types": 'generated/bt-types.md'
          - "bt-state": 'generated/bt-state.md'
  - MDAL:
      - Introduction: '../libmdal/docs/index.md'
      - MDMOD: '../libmdal/docs/MDMOD_SPECIFICATION.md'
      - MDCONF: '../libmdal/docs/MDCONF_SPECIFICATION.md'

markdown_extensions:
  - codehilite

use_directory_urls: False
