site_name: "Bintracker NG"

theme:
  name: 'material'
  hljs_languages:
    - scheme
    - xml

site_dir: 'documentation'

nav:
  - Home: index.md
  - Configuration: configuration.md
  - "Using The Console": console.md
  - "Bintracker API": 'generated/bintracker-core.md'

markdown_extensions:
  - codehilite

use_directory_urls: False
