site_name: MDAL

theme:
  name: 'material'
  hljs_languages:
    - scheme
    - xml

site_dir: 'docs/html'

nav:
  - Home: index.md
  - MDMOD: MDMOD_SPECIFICATION.md
  - MDCONF: MDCONF_SPECIFICATION.md
  - libmdal:
      - 'About libmdal': libmdal.md
      - 'API documentation':
          - 'mdal': 'generated/mdal.md'
          - 'md-config': 'generated/md-config.md'
          - 'md-types': 'generated/md-types.md'
          - 'md-parser': 'generated/md-parser.md'
          - 'md-command': 'generated/md-command.md'
          - 'md-helpers': 'generated/md-helpers.md'
          - 'Utilities':
              - 'md-note-table': 'generated/utils/md-note-table.md'

markdown_extensions:
  - codehilite
